name: Github Actions 실행하기

on:
  push:
    branches:
      - main

jobs:
  My-First-CICD-Job:
    runs-on: ubuntu-latest
    steps:
      - name: sample-web
        run: |
          pwd
          ls -al
      - name: echo text
        run: |
          echo "This is the first cicd step" >> a.txt
          ls -al
          cat a.txt
